# -*- coding: utf-8 -*-
"""PROJECT XLA 0205 03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwmhOUxiga8KjqhztDTsSLJYm3MFxGnC

**Bước 1: Tiến hành nhập liệu và khởi tạo hàm**
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

"""# Hàm kiểm tra ảnh đầu vào"""

def dieu_Chinh_Anh_Dau_Vao_lay_Canny_VIP(image):
  if len(image.shape) == 3:
      gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
  else:
      gray = image.copy()
  clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8))
  gray = clahe.apply(gray)
  gray = cv2.fastNlMeansDenoising(gray, None, 10, 7, 21)
  lap = cv2.Laplacian(gray, cv2.CV_64F)
  sharp = cv2.convertScaleAbs(gray - 0.5 * lap)
  blur = cv2.bilateralFilter(sharp, 9, 75, 75)
  binary = cv2.adaptiveThreshold( blur, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY_INV, 35, 5)
  kernel = np.ones((3,3), np.uint8)
  binary = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel, iterations=2)
  return binary

"""Hàm điều chỉnh ảnh đầu vào lấy nội dung"""

def dieu_Chinh_Anh_Dau_Vao_lay_NoiDung(image):
  image_Canny = dieu_Chinh_Anh_Dau_Vao_lay_Canny_VIP(image)
  image_lam_min = cv2.GaussianBlur(image_Canny, (3, 3), 0)
  image_erode = cv2.erode(image_lam_min, np.ones((3,3), np.uint8), iterations=1)
  return image_lam_min

def dieu_Chinh_Anh_Dau_Vao_lay_NoiDung_MD_SBD(image):
  img_open1 = cv2.morphologyEx(image, cv2.MORPH_OPEN, np.ones((7,7), np.uint8))
  return img_open1

"""Hàm tính góc"""

def tinh_goc(p1, p2, p3):
    v1 = p1 - p2
    v2 = p3 - p2
    cos_goc = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2) + 1e-6)
    goc = np.degrees(np.arccos(cos_goc))
    return goc

"""Hàm tìm contour hình chữ nhật bao ngoài khung trả lời"""

def tim_contour_bao_ngoai(image, minArea, maxArea, socanh):
  image_Copy = image.copy()
  contour, hierarchy = cv2.findContours(image_Copy, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
  contour_loc = []
  khung_can_tim = []
  for contour_phan in contour:
    dien_tich = cv2.contourArea(contour_phan)
    if (dien_tich > minArea) and (dien_tich < maxArea):
      peri = cv2.arcLength(contour_phan, True)
      approx = cv2.approxPolyDP(contour_phan, 0.02*peri, True)
      if (len(approx) == socanh):
        pts = approx.reshape(-1, 2)
        hop_le = True
        for i in range(4):
          p1 = pts[i]
          p2 = pts[(i+1) % 4]
          p3 = pts[(i+2) % 4]
          goc = tinh_goc(p1, p2, p3)
          if not (87 <= goc <= 93):
            hop_le = False
            break
        if not hop_le:
            continue
        x, y, w, h = cv2.boundingRect(contour_phan)
        if ((w > 455 and w < 550) and (h > 375 and h < 475)):
          continue
        contour_loc.append((approx, dien_tich, (x, y, w, h)))
  contour_loc.sort(key=lambda c: c[1], reverse=True)
  khung_kich_thuoc = []
  for approx, dien_tich, (x, y, w, h) in contour_loc:
        bi_loai = False
        for (cx, cy, cw, ch) in khung_kich_thuoc:
            xA = max(x, cx)
            yA = max(y, cy)
            xB = min(x + w, cx + cw)
            yB = min(y + h, cy + ch)
            interArea = max(0, xB - xA) * max(0, yB - yA)
            area_nho = min(w * h, cw * ch)
            if interArea > 0.9 * area_nho:
                bi_loai = True
                break
            if (x >= cx and y >= cy and x + w <= cx + cw and y + h <= cy + ch):
                nguong = 30
                canh_tiep_xuc = 0
                if abs(x - cx) <= nguong:
                    canh_tiep_xuc += 1
                if abs((x + w) - (cx + cw)) <= nguong:
                    canh_tiep_xuc += 1
                if abs(y - cy) <= nguong:
                    canh_tiep_xuc += 1
                if abs((y + h) - (cy + ch)) <= nguong:
                    canh_tiep_xuc += 1
                if canh_tiep_xuc >= 2:
                    bi_loai = True
                    break
        if not bi_loai:
            khung_can_tim.append((approx, dien_tich, w, h))
            khung_kich_thuoc.append((x, y, w, h))
  return khung_can_tim

"""Hàm tìm 4 góc của Hình chứ nhật"""

def tim_4_goc(arrayA):
  arrayA = arrayA.reshape(4, 2).astype("float32")
  mang_da_sap_xep = np.zeros((4, 2), dtype = "float32")
  tong = arrayA.sum(axis=1)
  hieu = np.diff(arrayA, axis=1)
  mang_da_sap_xep[0] = arrayA[np.argmin(tong)]
  mang_da_sap_xep[1] = arrayA[np.argmin(hieu)]
  mang_da_sap_xep[2] = arrayA[np.argmax(tong)]
  mang_da_sap_xep[3] = arrayA[np.argmax(hieu)]
  return mang_da_sap_xep

"""Hàm sắp xếp contour"""

def sap_xep_contour(contours):
    rects = [cv2.boundingRect(c[0]) for c in contours]
    heights = [h for (x, y, w, h) in rects]
    median_h = np.median(heights) if heights else 50
    gap_threshold = 0.5 * median_h
    contours_info = [(c, r[0], r[1]) for c, r in zip(contours, rects)]
    contours_info.sort(key=lambda t: t[2])
    rows = []
    if contours_info:
        current_row = [contours_info[0]]
        for i in range(1, len(contours_info)):
            last_y = current_row[-1][2]
            cur_y = contours_info[i][2]
            if cur_y - last_y < gap_threshold:
                current_row.append(contours_info[i])
            else:
                rows.append(current_row)
                current_row = [contours_info[i]]
        rows.append(current_row)
    rows.reverse()
    sorted_contours = []
    for row in rows:
        row.sort(key=lambda t: t[1])
        for cnc, _, _ in row:
            sorted_contours.append(cnc)
    return sorted_contours

"""Cắt phần 3 thành 6 phần nhỏ"""

def cat_P3_thanh_6_phan(image):
  h, w = image.shape[:2]
  khoang_cot = [0, 1/6, 2/6, 3/6, 4/6, 5/6, 1]
  danh_sach_anh_da_cat = []
  for i in range(len(khoang_cot) - 1):
    x_start = int(khoang_cot[i] * w)
    x_end = int(khoang_cot[i+1] * w)
    anh_da_cat = image[:, x_start:x_end]
    danh_sach_anh_da_cat.append(anh_da_cat)
  return danh_sach_anh_da_cat

"""Hàm tìm đáp án

Hàm tìm ngưỡng Otsu (tự động tìm ngưỡng, nếu như lớn hơn ngưỡng thì là đã khoanh, nhỏ hơn là chưa có khoanh)
"""

def tim_Nguong_Otsu(ratios):
    data = np.array(ratios) * 255
    data = data.astype(np.uint8)
    nguong_otsu, _ = cv2.threshold(data, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    return nguong_otsu / 255.0

"""Chấm phần 1 theo ma trận"""

def giai_ma_phan1_tu_ma_tran(ma_tran_ti_le_to, nguong_otsu):
    so_hang, so_cot = ma_tran_ti_le_to.shape
    ket_qua_tung_phan = []
    kq = [0, 1, 2, 3]
    for i in range(so_hang):
        kq_chon = np.where(ma_tran_ti_le_to[i, :] > nguong_otsu)[0]
        if len(kq_chon) == 0:
            ket_qua_tung_phan.append("")
        elif len(kq_chon) > 1:
            values_selected = ma_tran_ti_le_to[i, kq_chon]
            max_idx_in_selected = np.argmax(values_selected)
            max_val = values_selected[max_idx_in_selected]
            others = np.delete(values_selected, max_idx_in_selected)
            if np.all(max_val > 1.2 * others):
                idx = kq_chon[max_idx_in_selected]
                ket_qua_tung_phan.append(kq[idx])
            else:
                ket_qua_tung_phan.append("")
        else:
            idx = kq_chon[0]
            if 0 <= idx < len(kq):
                ket_qua_tung_phan.append(kq[idx])
            else:
                idx = np.argmax(ma_tran_ti_le_to[i, :])
                ket_qua_tung_phan.append(kq[idx])
    return ket_qua_tung_phan
def cham_phan_1_ma_tran(ds_image):
    ket_qua_tong_the = []
    ty_le_cot = [0.0, 0.25, 0.5, 0.75, 1.0]
    ty_le_hang = [0.0, 1/10, 2/10,  3/10, 4/10, 5/10, 6/10, 7/10, 8/10, 9/10, 1]
    for o in ds_image:
        ma_tran_ti_le_to = tao_Ma_Tran_Dap_An(o, ty_le_hang, ty_le_cot)
        ket_qua_tung_phan = giai_ma_phan1_tu_ma_tran(ma_tran_ti_le_to, 0.3)
        ket_qua_tong_the.append(ket_qua_tung_phan)
    return ket_qua_tong_the

"""Chấm phần 2 theo ma trận"""

def cham_P2_theo_ma_tran(ma_tran_ty_le, nguong_otsu):
  so_hang, so_cot = ma_tran_ty_le.shape
  ket_qua = []
  for i in range(so_hang):
      nguong_toi_thieu = nguong_otsu
      ti_le_A_thu = ma_tran_ty_le[i, 0]
      ti_le_B_thu = ma_tran_ty_le[i, 1]
      if (ti_le_A_thu < 0.25) and (ti_le_B_thu < 0.25):
          dap_an = ""
      else:
          if (ti_le_A_thu > nguong_toi_thieu) and (ti_le_B_thu > nguong_toi_thieu):
              if (ti_le_A_thu > ti_le_B_thu*1.2):
                  dap_an = 1
              elif (ti_le_A_thu*1.2 < ti_le_B_thu):
                  dap_an = 0
              else:
                  dap_an = ""
          elif (ti_le_A_thu >= nguong_toi_thieu) and (ti_le_B_thu < nguong_toi_thieu):
              dap_an = 1
          elif (ti_le_A_thu < nguong_toi_thieu) and (ti_le_B_thu >= nguong_toi_thieu):
              dap_an = 0
          else:
              dap_an = ""
      ket_qua.append(dap_an)
  return ket_qua
def cham_phan2_theo_o(ds_anh):
    ket_qua = []
    danh_sach_cau = ds_anh
    for cau in danh_sach_cau:
      ty_le_hang = [0.0, 0.25, 0.5, 0.75, 1]
      ty_le_cot  = [0.0, 0.5, 1]
      ma_tran_ty_le = tao_Ma_Tran_Dap_An(cau, ty_le_hang, ty_le_cot)
      kq_phan = cham_P2_theo_ma_tran(ma_tran_ty_le, 0.3)
      ket_qua.append(kq_phan)
    return ket_qua

def cham_phan3_theo_o(ds_anh):
    ket_qua = []
    for idx, o in enumerate(ds_anh):
        h, w = o.shape[:2]
        new_h = int(h * 33/40)
        y_start = h - new_h
        new_w = int(w * 4 / 5)
        x_start = w - new_w
        x_end = int(w - w*1/10)
        y_end = int(h - h*0.2/10)
        vung_dap_an = o[y_start:y_end, x_start:x_end]
        ty_le_hang = [0.0, 1/12, 2/12, 3/12, 4/12, 5/12, 6/12, 7/12, 8/12, 9/12, 10/12, 11/12, 1]
        ty_le_cot  = [0.0, 0.5/2, 1/2, 1.5/2, 1]
        ma_tran_ty_le = tao_Ma_Tran_Dap_An(vung_dap_an, ty_le_hang, ty_le_cot)
        so = giai_Ma_Tu_Ma_Tran(ma_tran_ty_le, 0.3)
        ket_qua.append(so)
    return ket_qua

def ghep_so(ky_tu):
    if len(ky_tu) == 0:
        return "null"
    dau_am = False
    so = ""
    co_phay = False
    for i, kt in enumerate(ky_tu):

        if kt == "null":
            continue
        if kt == "-":
            dau_am = True
        elif kt == ",":
            if co_phay:
                return ""
            co_phay = True
            so += "."
        else:
            so += kt
    if so == "":
        return ""
    if dau_am:
        so = "-" + so
    return so

"""Hàm tạo ma trận đáp án"""

def tao_Ma_Tran_Dap_An(image, ty_le_hang, ty_le_cot):
    cao, rong = image.shape[:2]
    so_hang = len(ty_le_hang) -1
    so_cot = len(ty_le_cot) - 1
    ma_Tran = np.zeros((so_hang, so_cot), dtype=np.int32)
    ma_Tran_ti_le_to = np.zeros((so_hang, so_cot), dtype=np.float32)
    for i in range(so_hang):
        y_start = int(ty_le_hang[i] * cao)
        y_end = int(ty_le_hang[i+1] * cao)
        for j in range(so_cot):
            x_start = int(ty_le_cot[j]   * rong)
            x_end   = int(ty_le_cot[j+1] * rong)
            o_anh = image[y_start:y_end, x_start:x_end]
            if o_anh.size == 0:
                continue
            h, w = o_anh.shape
            h_bd = int(h * 0.4)
            h_kt = int(h * 0.6)
            w_bd = int(w * 0.4)
            w_kt = int(w * 0.6)
            vung_trung_tam = o_anh[h_bd:h_kt, w_bd:w_kt]
            so_pixel_to = np.count_nonzero(vung_trung_tam)
            tong_pixel = vung_trung_tam.size
            ti_le_to = so_pixel_to / tong_pixel
            ma_Tran_ti_le_to[i, j] = ti_le_to
    return ma_Tran_ti_le_to

"""Tạo ma trận chấm mã đề"""

def tao_Ma_Tran_Ma_De(image, ty_le_hang, ty_le_cot):
    cao, rong = image.shape[:2]
    so_hang = len(ty_le_hang) -1
    so_cot = len(ty_le_cot) - 1
    ma_Tran = np.zeros((so_hang, so_cot), dtype=np.int32)
    ma_Tran_ti_le_to = np.zeros((so_hang, so_cot), dtype=np.float32)
    for i in range(so_hang):
        y_start = int(ty_le_hang[i]   * cao)
        y_end = int(ty_le_hang[i+1] * cao)
        for j in range(so_cot):
            x_start = int(ty_le_cot[j]   * rong)
            x_end   = int(ty_le_cot[j+1] * rong)
            o_anh = image[y_start:y_end, x_start:x_end]
            if o_anh.size == 0:
                continue
            nguong_To, image_phan_nguong= cv2.threshold(o_anh, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
            h, w = image_phan_nguong.shape
            mask = np.zeros((h, w), dtype=np.uint8)
            cx, cy = w // 2, h // 2
            r = int(min(h, w) * 0.35)
            cv2.circle(mask, (cx, cy), r, 255, -1)
            vung_trung_tam = cv2.bitwise_and(image_phan_nguong, image_phan_nguong, mask=mask)
            so_pixel_to = np.count_nonzero(vung_trung_tam)
            tong_pixel = np.count_nonzero(mask)
            ti_le_to = so_pixel_to / tong_pixel
            ma_Tran_ti_le_to[i, j] = ti_le_to
    return ma_Tran_ti_le_to

"""Hàm giải mã phần 3 từ ma trận"""

def giai_Ma_Tu_Ma_Tran(ma_Tran, nguong_otsu):
  so_hang, so_cot = ma_Tran.shape
  if so_hang > 1 and so_cot > 3:
    ma_Tran[0, 1:4] = 0
    ma_Tran[1, 0] = 0
    ma_Tran[1, 3] = 0
  ky_tu_list = []
  for j in range(so_cot):
    hang_duoc_to = np.where((ma_Tran[:, j] > nguong_otsu) & (ma_Tran[:, j] > 0.25))[0]
    if (len(hang_duoc_to) == 0):
      ky_tu = ""
    elif (len(hang_duoc_to) > 1):
      values_selected = ma_Tran[hang_duoc_to, j]
      max_idx_in_selected = np.argmax(values_selected)
      max_val = values_selected[max_idx_in_selected]
      others = np.delete(values_selected, max_idx_in_selected)
      if np.all(max_val > 1.2 * others):
          idx = hang_duoc_to[max_idx_in_selected]
          if idx == 0:
              ky_tu = "-"
          elif idx == 1:
              ky_tu = ","
          else:
              ky_tu = str(idx-2)
      else:
          ky_tu = "Co nhieu hon 1 dap an"
    else:
      idx = hang_duoc_to[0]
      if idx == 0:
        ky_tu = "-"
      elif idx == 1:
        ky_tu = ","
      else:
        ky_tu = str(idx-2)
    ky_tu_list.append(ky_tu)
  ket_qua = ""
  da_co_dau_phay = False
  start = 0
  n = len(ky_tu_list)
  while start < n and ky_tu_list[start] == "":
    start += 1
  if start == n:
    ket_qua = ""
  else:
    sub = ky_tu_list[start:]

    for i, kt in enumerate(sub):
      if kt == "":
        continue
      if kt == "Co nhieu hon 1 dap an":
        return ""

      if kt == "-":
        if i != 0:
          return ""
        ket_qua += kt

      elif kt == ",":
        if da_co_dau_phay or i == 0 or sub[i-1] == "-":
          return ""
        ket_qua += kt
        da_co_dau_phay = True

      elif kt.isdigit():
        ket_qua += kt

      else:
        return ""
  if "," in ket_qua:
    phan_nguyen, phan_thap_phan = ket_qua.split(",")
    if all(c == "0" for c in phan_thap_phan):
      ket_qua = phan_nguyen
  return ghep_so(ket_qua)

"""Hàm đọc phần số báo danh"""

def docSBD(anhSBD):
  ket_qua = []
  anh_mo = anhSBD
  h, w = anh_mo.shape[:2]
  ty_le_hang = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  ty_le_cot  = [0, 1/6, 2/6, 3/6, 4/6, 5/6, 1.0]
  ma_tran_ty_le = tao_Ma_Tran_Ma_De(anh_mo, ty_le_hang, ty_le_cot)
  nguong_otsu = tim_Nguong_Otsu(ma_tran_ty_le)
  nguong_toi_thieu = nguong_otsu
  ket_qua = giai_ma_SBD_Ma_De(ma_tran_ty_le, nguong_otsu)
  return ket_qua

"""Hàm đọc mã đề"""

def doc_Ma_De(anhMD):
  ket_qua = []
  anh_mo = anhMD
  h, w = anh_mo.shape[:2]
  ty_le_hang = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  ty_le_cot  = [0, 1/3, 2/3, 1]
  ma_tran_ty_le = tao_Ma_Tran_Ma_De(anh_mo, ty_le_hang, ty_le_cot)
  nguong_otsu = tim_Nguong_Otsu(ma_tran_ty_le)
  nguong_toi_thieu = nguong_otsu
  ket_qua = giai_ma_SBD_Ma_De(ma_tran_ty_le, nguong_otsu)
  return ket_qua

"""Hàm giải mã ma trận SBD và Mã đề"""

def giai_ma_SBD_Ma_De(ma_Tran, nguong_otsu):
  so_hang, so_cot = ma_Tran.shape
  ky_tu_list = []
  for j in range(so_cot):
    hang_duoc_to = np.where((ma_Tran[:, j] > nguong_otsu) & (ma_Tran[:, j] > 0.3))[0]
    if (len(hang_duoc_to) == 0):
      ky_tu = ""
    elif (len(hang_duoc_to) > 1):
      values_selected = ma_Tran[hang_duoc_to, j]
      max_idx_in_selected = np.argmax(values_selected)
      max_val = values_selected[max_idx_in_selected]
      others = np.delete(values_selected, max_idx_in_selected)
      if np.all(max_val > 1.02 * others):
          idx = hang_duoc_to[max_idx_in_selected]
          ky_tu = str(idx)
      else:
          ky_tu = ""
    else:
      idx = hang_duoc_to[0]
      ky_tu = str(idx)
    ky_tu_list.append(ky_tu)
  return ghep_so(ky_tu_list)

"""


# Hàm chỉnh xử lý ảnh"""
duong_dan_anh_dau_vao = input("Nhap duong dan cua anh dau vao tai day: ")
if (duong_dan_anh_dau_vao == ""):
  raise Exception("Duong dan anh rong")
image_goc_ch_chinh = cv2.imread(duong_dan_anh_dau_vao)
if (image_goc_ch_chinh is None):
  raise Exception("Duong dan nay khong co anh")

h, w = image_goc_ch_chinh.shape[:2]
new_w = int(w * 0.96)
new_h = int(h * 0.96)
x_start = (w - new_w) // 2
y_start = (h - new_h) // 2
anh_goc_cat = image_goc_ch_chinh[y_start:y_start+new_h, x_start:x_start+new_w]

A4_width = 2480
A4_height = 3508
image = cv2.resize(anh_goc_cat, (A4_width, A4_height), interpolation=cv2.INTER_CUBIC)

image_DieuChinh = dieu_Chinh_Anh_Dau_Vao_lay_Canny_VIP(image)

image_NoiDung = dieu_Chinh_Anh_Dau_Vao_lay_NoiDung(image)

"""Sử dụng contour để bắt khung của từng phần muốn trả lời"""

image_copy = image.copy()
image_Canny_Copy = image_DieuChinh.copy()
khung_can_tim = tim_contour_bao_ngoai(image_Canny_Copy, 60000, 600000, 4)
khung_can_tim_da_sap_xep = sap_xep_contour(khung_can_tim)
approx_can_tim_da_sap_xep = []
for i, (approx, dien_tich, w, h) in enumerate(khung_can_tim_da_sap_xep):
  approx_can_tim_da_sap_xep.append(approx)

"""Tìm 4 góc viền ngoài của contour"""

contour_da_sap_xep = []
for contour_phan in approx_can_tim_da_sap_xep:
  contour_sap_xep = tim_4_goc(contour_phan)
  contour_da_sap_xep.append(contour_sap_xep)

"""xử lý warp ảnh"""

cac_phan_anh_da_duoc_warped = []
for i in range(len(contour_da_sap_xep)):
  contour_Phan = contour_da_sap_xep[i]
  chieu_Rong_A = np.sqrt(np.pow(contour_Phan[1][0] - contour_Phan[0][0], 2) + np.pow(contour_Phan[1][1] - contour_Phan[0][1], 2))
  chieu_Rong_B = np.sqrt(np.pow(contour_Phan[2][0] - contour_Phan[3][0], 2) + np.pow(contour_Phan[2][1] - contour_Phan[3][1], 2))
  chieu_Dai_A = np.sqrt(np.pow(contour_Phan[3][0] - contour_Phan[0][0], 2) + np.pow(contour_Phan[3][1] - contour_Phan[0][1], 2))
  chieu_Dai_B = np.sqrt(np.pow(contour_Phan[2][0] - contour_Phan[1][0], 2) + np.pow(contour_Phan[2][1] - contour_Phan[1][1], 2))
  max_Chieu_Rong = max(int(chieu_Rong_A), int(chieu_Rong_B))
  max_Chieu_Dai = max(int(chieu_Dai_A), int(chieu_Dai_B))
  vi_tri_sau_khi_warp = np.array([[0, 0], [max_Chieu_Rong - 1, 0], [max_Chieu_Rong - 1,max_Chieu_Dai - 1], [0, max_Chieu_Dai - 1]], dtype = "float32")
  ma_tran_bien_doi = cv2.getPerspectiveTransform(contour_Phan, vi_tri_sau_khi_warp)
  anh_warped = cv2.warpPerspective(image, ma_tran_bien_doi, (max_Chieu_Rong, max_Chieu_Dai))
  cac_phan_anh_da_duoc_warped.append(anh_warped)

"""Xử lý bên trong ảnh, nhị phân hóa ảnh và xử lý nhiễu bằng opening, closing"""

kernel = np.ones((3, 3), np.uint8)
cac_phan_anh_warped_xu_ly = []
for i in range(len(cac_phan_anh_da_duoc_warped)):
  phan_anh = cac_phan_anh_da_duoc_warped[i]
  phan_anh_DieuChinh = dieu_Chinh_Anh_Dau_Vao_lay_NoiDung(phan_anh)
  cac_phan_anh_warped_xu_ly.append(phan_anh_DieuChinh)

"""Tách thành từng vùng để dễ xử lý"""

anh_tu_luan = cac_phan_anh_warped_xu_ly[0:6]
vung_anh_dung_sai_chua_chinh = cac_phan_anh_da_duoc_warped[6:14]
vung_anh_trac_nghiem = cac_phan_anh_warped_xu_ly[14:18]
anh_ma_de = cac_phan_anh_da_duoc_warped[-1]
anh_SBD = cac_phan_anh_da_duoc_warped[-2]

"""Xử lý phần ảnh Đúng/Sai"""

vung_anh_dung_sai = []
for i, imageDS in enumerate(vung_anh_dung_sai_chua_chinh):
  h, w = imageDS.shape[:2]
  if (i%2 == 0):
    new_h = int(h * 65 / 100)
    y_start = h - new_h
    y_end = int(h - h*0.02)
    new_w = int(w * 34.5 / 50)
    x_start = w - new_w
    x_end = int(w - w*0.01)
    imageDS_Cat = imageDS[y_start:y_end, x_start:x_end]
  else:
    new_h = int(h * 65 / 100)
    y_start = h - new_h
    y_end = int(h - h*0.02)
    new_w = int(w * 47 / 50)
    x_start = w - new_w
    x_end = int(w - w*0.05)
    imageDS_Cat = imageDS[y_start:y_end, x_start:x_end]
  imageDS_cat_chinh_sua = dieu_Chinh_Anh_Dau_Vao_lay_NoiDung(imageDS_Cat)
  vung_anh_dung_sai.append(imageDS_cat_chinh_sua)

"""Xử lý vùng ảnh tự luận

Ta tạo ảnh tự luận cắt đã chỉnh sửa
"""

phan3 = cham_phan3_theo_o(anh_tu_luan)

vung_anh_TN_sau_cat = []
for i in range(len(vung_anh_trac_nghiem)):
  h, w = vung_anh_trac_nghiem[i].shape[:2]
  new_h = int(h * 45.5 / 50)
  new_w = int(w * 4.2 / 5)
  y_start = h - new_h
  x_start = w - new_w
  x_end = int(w - w*0.1/10)
  y_end = int(h - h*0.2/10)
  image_sau_cat = vung_anh_trac_nghiem[i][y_start:y_end, x_start:x_end]
  vung_anh_TN_sau_cat.append(image_sau_cat)

phan1 = cham_phan_1_ma_tran(vung_anh_TN_sau_cat)

phan2 = cham_phan2_theo_o(vung_anh_dung_sai)

"""Phần đọc số báo danh"""

anh_SBD_sau_Canny = dieu_Chinh_Anh_Dau_Vao_lay_Canny_VIP(anh_SBD)
anh_SBD_da_sua = dieu_Chinh_Anh_Dau_Vao_lay_NoiDung_MD_SBD(anh_SBD_sau_Canny)
sbd = docSBD(anh_SBD_da_sua)

"""Phần đọc mã đề"""

anh_ma_de_sau_Canny = dieu_Chinh_Anh_Dau_Vao_lay_Canny_VIP(anh_ma_de)
anh_ma_de_da_sua = dieu_Chinh_Anh_Dau_Vao_lay_NoiDung_MD_SBD(anh_ma_de_sau_Canny)
kq_Ma_de = doc_Ma_De(anh_ma_de_da_sua)

"""**PHẦN CHẤM ĐIỂM(Hưng)**"""

import json
import re

def xuat_output_json(phan1, phan2, phan3, sbd, mdt, duong_dan_anh_dau_vao):


    phan1 = [item for sublist in phan1 for item in sublist]
    fc = {
        str(i+1): [val] if val != "" else []
        for i, val in enumerate(phan1)
    }


    tf_flat = []
    for row in phan2:
        for val in row:
            if isinstance(val, int):
                tf_flat.append(val)
            else:
                tf_flat.append("")

    tf = {
        str(i+1): [val] if val != "" else []
        for i, val in enumerate(tf_flat)
    }


    dg = {
        str(i+1): str(val) if val != "" else ""
        for i, val in enumerate(phan3)
    }

    output = [{
        "org": duong_dan_anh_dau_vao,
        "out": "",
        "warn": "",
        "err": [],
        "res": {
            "fc": fc,
            "tf": tf,
            "dg": dg
        },
        "sbd": sbd,
        "mdt": mdt
    }]


    json_str = json.dumps(output, ensure_ascii=False, indent=4)

    json_str = re.sub(r'\[\s+', '[', json_str)   # bỏ space sau [
    json_str = re.sub(r'\s+\]', ']', json_str)   # bỏ space trước ]


    with open("output.json", "w", encoding="utf-8") as f:
        f.write(json_str)

    print("Đã xuất JSON")
    print(json_str)

xuat_output_json(
    phan1,
    phan2,
    phan3,
    sbd,
    kq_Ma_de,
    duong_dan_anh_dau_vao
)

"""kho_dap_an.JSON demo file dap an

"""

import json

kho_dap_an = [
    {
        "org": "",
        "out": "",
        "warn": "",
        "err": [],
        "res": {
            "fc": {
                str(i+1): [ans] for i, ans in enumerate([
                    0,1,1,2,0,3,2,1,3,0,
                    2,1,3,0,1,2,3,1,2,0,
                    1,2,0,3,1,2,0,3,1,0,
                    1,2,0,3,1,2,0,3,1,0
                ])
            },

            "tf": {
                str(i+1): ([val] if isinstance(val, int) else [])
                for i, val in enumerate([
                    1,0,1,0,
                    0,0,1,1,
                    0,1,0,1,
                    1,0,1,0,
                    0,1,1,0,
                    1,0,1,0,
                    1,1,1,1,
                    0,0,0,0
                ])
            },

            "dg": {
                str(i+1): str(val) if val != "" else ""
                for i, val in enumerate([
                    -134,
                    1003,
                    3.15,
                    81.3,
                    -2.5,
                    0
                ])
            }
        },

        "sbd": "",
        "mdt": "014"
    }
]

with open("kho_dap_an.json", "w", encoding="utf-8") as f:
    json.dump(kho_dap_an, f, ensure_ascii=False, indent=4)

print(" Đã tạo kho đáp án ")

import json
import os

def doc_file_json(ten_file):
    with open(ten_file, "r", encoding="utf-8") as f:
        return json.load(f)

def tinh_ket_qua_phan1_fc(fc_hs, fc_dung):
    ket_qua = []
    so_cau_dung = 0

    for i in range(1, 41):
        hs = fc_hs.get(str(i), [])
        dung = fc_dung.get(str(i), [])

        if hs == dung and len(hs) > 0:
            ket_qua.append("D")
            so_cau_dung += 1
        else:
            ket_qua.append("S")

    return so_cau_dung, ket_qua



def tinh_ket_qua_phan2_tf(tf_hs, tf_dung):
    ket_qua = []
    so_cau_dung = 0

    for i in range(1, 33):
        hs = tf_hs.get(str(i), [])
        dung = tf_dung.get(str(i), [])

        cau_kq = []

        for j in range(4):
            if (j in hs) == (j in dung):
                cau_kq.append("D")
                if j in dung:
                    so_cau_dung += 1
            else:
                cau_kq.append("S")

        ket_qua.append(cau_kq)

    return so_cau_dung, ket_qua




def tinh_ket_qua_phan3_dg(dg_hs, dg_dung):
    ket_qua = []
    so_cau_dung = 0

    for i in range(1, 7):
        hs = dg_hs.get(str(i), "")
        dung = dg_dung.get(str(i), "")

        try:
            hs_val = float(hs.replace(",", "."))
            dung_val = float(dung.replace(",", "."))

            if hs_val == dung_val:
                ket_qua.append("D")
                so_cau_dung += 1
            else:
                ket_qua.append("S")
        except:
            ket_qua.append("S")

    return so_cau_dung, ket_qua




def luu_ket_qua(ket_qua_moi):

    ten_file = "ket_qua.json"

    if os.path.exists(ten_file):
        with open(ten_file, "r", encoding="utf-8") as f:
            try:
                danh_sach = json.load(f)
            except:
                danh_sach = []
    else:
        danh_sach = []

    danh_sach.append(ket_qua_moi)

    with open(ten_file, "w", encoding="utf-8") as f:
        json.dump(danh_sach, f, ensure_ascii=False, indent=4)




def cham_diem():
    output = doc_file_json("output.json")
    kho_dap_an = doc_file_json("kho_dap_an.json")

    for bai in output:
        sbd = bai.get("sbd", "unknown")
        ma_de = str(bai.get("mdt")).zfill(3)

        res_dung = None
        for de in kho_dap_an:
            if str(de.get("mdt")).zfill(3) == ma_de:
                res_dung = de["res"]
                break

        if res_dung is None:
            raise Exception("Ma de khong khop!")

        res_hs = bai["res"]
        dung1, kq1 = tinh_ket_qua_phan1_fc(
            res_hs["fc"], res_dung["fc"]
        )

        dung2, kq2 = tinh_ket_qua_phan2_tf(
            res_hs["tf"], res_dung["tf"]
        )

        dung3, kq3 = tinh_ket_qua_phan3_dg(
            res_hs["dg"], res_dung["dg"]
        )

        tong_dung = dung1 + dung2 + dung3

        tong_so_cau = 40 + 32*4 + 6

        diem = round(10 * tong_dung / tong_so_cau, 2)

        print("===== KẾT QUẢ =====")
        print("SBD:", sbd)
        print("Mã đề:", ma_de)
        print("Điểm:", diem)





if __name__ == "__main__":
    cham_diem()
